#Word Cloud
#install.packages('tm')
#install.packages ('wordcloud')
#install.packages ('RColorBrewer')
library(tm)
library(wordcloud)
library(RColorBrewer)
speech='D:\\Programming Tutorials\\Machine Learning\\WhatsApp Home.txt'
myTxt=readLines(speech)
tCorpus=Corpus(VectorSource(myTxt))
myData=tm_map(tCorpus,stripWhitespace)
myData=tm_map(myData,tolower)
myData=tm_map(myData,removeNumbers)
myData=tm_map(myData,removePunctuation)
myData=tm_map(myData,removeWords, stopwords('English'))
myData=tm_map(myData,removeWords, c('will','vijaya','blore','like','can','and','omitted','the','our','that','for','are','also','more','has','must','have','should','this','with'))
inspect(myData[1:10])
tdmText=TermDocumentMatrix(myData)
tdm=as.matrix(tdmText)
v=sort(rowSums(tdm),decreasing = TRUE)
summary(v)
wordcloud(myData, scale=c(2,0.5), max.words=120, random.order=FALSE, rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(8,'Accent'))